"""
Django settings for django1_demo project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'menp-@6f-upfiaotvjr=-3kv6@bw@yqn5g1x55uzij72#8a@dl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django1_demo.urls'

# 跨域
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django1_demo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },

    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '114.113.127.115:1521/zrty',
        'USER': 'ibp',
        'PASSWORD': 'ibppwd',
    },

    'ibpcs': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'zrty',
        'HOST': '114.113.127.115',
        'PORT': 1521,
        'USER': 'ibpcs',
        'PASSWORD': 'ibpcs2021',
    },

    # 'postgresql': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'mydb',
    #     'USER': 'work1',
    #     'PASSWORD': '670921',
    #     'HOST': 'localhost',
    #     'PORT': 5432,
    #     'OPTIONS': {
    #         'options': '-c search_path=mytest',
    #     },
    # },

    # def get_new_connection(self, conn_params):
    #     conn = Database.connect(**conn_params)
    #     conn.encoders[SafeText] = conn.encoders[six.text_type]
    #     if bytes in conn.encoders:
    #         conn.encoders[SafeBytes] = conn.encoders[bytes]
    #     return conn
    'mysql': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zrtydata',
        'USER': 'root',
        'PASSWORD': '2wsxCvgy7',
        'HOST': 'localhost',
        'PORT': 3306,
    },
}

# 自定义用户模型类
AUTH_USER_MODEL = 'user.UserInfo'

LOGIN_URL = '/admin/login/'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
